import importlib.util
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "table_provenance.py"
spec = importlib.util.spec_from_file_location("table_provenance", SCRIPT)
tp = importlib.util.module_from_spec(spec)
spec.loader.exec_module(tp)


def test_build_rows_returns_table_3_acc_roberta():
    """Test that Table 3 Acc column contains roberta-base row with correct value."""
    rows = tp.build_rows(REPO_ROOT)
    roberta_rows = [r for r in rows if r["table"] == "Table 3" and r["column"] == "Acc" 
                    and "roberta-base" in r["row"]]
    assert len(roberta_rows) > 0, "No roberta-base rows found in Table 3 Acc column"
    assert any(r["value"] == "0.9325" for r in roberta_rows), (
        f"Expected value 0.9325 in roberta-base rows, got {[r['value'] for r in roberta_rows]}"
    )


def test_build_rows_returns_recommender_table():
    """Test that Table recommender contains recommender_rules row with correct agreement."""
    rows = tp.build_rows(REPO_ROOT)
    recommender_rows = [r for r in rows if r["table"] == "Table recommender" 
                        and r["row"] == "recommender_rules" 
                        and r["column"] == "Agree. (%)"]
    assert len(recommender_rows) > 0, "No recommender_rules Agree. (%) rows found"
    assert any(r["value"] == "100.0" for r in recommender_rows), (
        f"Expected value 100.0 in recommender_rules Agree. (%), got {[r['value'] for r in recommender_rows]}"
    )


def test_build_rows_returns_table_5_verifier_row():
    """Test that Table 5 contains the gold-only verifier's held-out accuracy."""
    rows = tp.build_rows(REPO_ROOT)
    verifier_rows = [r for r in rows if r["table"] == "Table 5"
                      and r["row"] == "verifier (gold-only RoBERTa)"
                      and r["column"] == "held-out accuracy"]
    assert len(verifier_rows) > 0, "No verifier row found in Table 5"
    assert any(r["value"] == "0.8555" for r in verifier_rows), (
        f"Expected value 0.8555 in the verifier row, got {[r['value'] for r in verifier_rows]}"
    )


def test_all_files_exist():
    """Test that all file paths in rows exist relative to REPO_ROOT."""
    rows = tp.build_rows(REPO_ROOT)
    missing_files = []
    for row in rows:
        # Skip "pending" value rows (they reference files that don't exist yet)
        if row.get("value") == "pending":
            continue
        file_path = REPO_ROOT / row["file"]
        if not file_path.exists():
            missing_files.append((row, file_path))

    assert not missing_files, (
        f"Missing files: {[(r['file'], p) for r, p in missing_files]}"
    )


def test_render_output():
    """Test that render() produces valid markdown table with correct structure."""
    rows = tp.build_rows(REPO_ROOT)
    output = tp.render(rows)
    lines = output.split("\n")

    # Assert first line is the header
    assert lines[0] == "# Table provenance (generated by scripts/table_provenance.py)", (
        f"First line should be header, got: {lines[0]}"
    )

    # Assert line 3 (index 2) is the column header
    assert lines[2] == "| table | row | column | value | file |", (
        f"Line 3 should be column header, got: {lines[2]}"
    )

    # Assert line 4 (index 3) is the separator with exactly 5 cells
    assert lines[3] == "|---|---|---|---|---|", (
        f"Line 4 should be separator, got: {lines[3]}"
    )

    # Assert every data line has exactly 5 cells
    data_lines = [line for line in lines[4:] if line.strip()]  # Skip empty lines
    assert len(data_lines) == len(rows), (
        f"Expected {len(rows)} data lines, got {len(data_lines)}"
    )

    for i, line in enumerate(data_lines):
        cells = [c.strip() for c in line.split("|")[1:-1]]  # Remove outer pipes
        assert len(cells) == 5, (
            f"Line {i} should have 5 cells, got {len(cells)}: {line}"
        )


def test_main_with_output_option():
    """Test that main() respects --output option."""
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)
        output_file = tmp_path / "custom.md"

        # Call main with custom output path
        result = tp.main(["--output", str(output_file)])

        assert result == 0, "main() should return 0"
        assert output_file.exists(), f"Output file should exist at {output_file}"

        # Verify default output file is untouched
        default_file = REPO_ROOT / "docs" / "TABLE_PROVENANCE.md"
        original_mtime = default_file.stat().st_mtime

        # Call main again with custom output (should not touch default)
        tp.main(["--output", str(tmp_path / "another.md")])
        assert default_file.stat().st_mtime == original_mtime, (
            "Default output file should not be modified"
        )

        # Verify custom output has correct structure
        content = output_file.read_text()
        assert content.startswith("# Table provenance"), "Output should have correct header"
        lines = content.split("\n")
        assert lines[2] == "| table | row | column | value | file |", (
            "Output should have correct column header"
        )


def test_build_rows_returns_table_2_loop_rows_from_out_g3():
    """The corrected-warmup promptillery cells point at their arm's metrics.json under out/g3."""
    rows = tp.build_rows(REPO_ROOT)
    loop = [r for r in rows if r["table"] == "Table 2" and "promptillery (" in r["row"]]
    huffpost_10 = [r for r in loop if r["row"] == "roberta_base promptillery (10 cycles)" and r["column"] == "huffpost"]
    assert len(huffpost_10) == 1, f"expected one HuffPost 10-cycle row, got {huffpost_10}"
    assert huffpost_10[0]["value"] == "55.49"
    assert huffpost_10[0]["file"].startswith("out/g3/ablation_g3_huffpost_roberta_base_")
    assert huffpost_10[0]["file"].endswith("/metrics.json")
    assert (REPO_ROOT / huffpost_10[0]["file"]).exists()
    assert any(r["row"] == "roberta_base promptillery (1 cycle)" for r in loop)


def test_table2_loop_rows_latest_ablation_dir_wins(tmp_path):
    """Two ablation directories for one dataset: only the later timestamp is indexed."""
    import json as _json
    g3 = tmp_path / "out" / "g3"
    for stamp, acc in (("20260101_000000", 0.10), ("20260922_120000", 0.90)):
        arm = g3 / f"ablation_g3_sst2_roberta_base_transformers_{stamp}" / f"g3_sst2_roberta_base_transformers_cycles-5_{stamp}_000000_s13_ab_cd"
        arm.mkdir(parents=True)
        (arm / "metrics.json").write_text(_json.dumps({"heldout_test": {"accuracy": acc}}))
    rows = tp._table2_loop_rows(tmp_path)
    assert [r["value"] for r in rows] == ["90.00"]
    assert "20260922_120000" in rows[0]["file"]


def test_table2_loop_rows_bs_rerun_dir_wins_and_tags_value(tmp_path):
    """An out-of-memory re-run at batch 16 is a later ``_bs16`` directory: it is indexed, tagged, and the
    failed batch-32 arms (no held-out accuracy) are skipped."""
    import json as _json
    g3 = tmp_path / "out" / "g3"
    failed = g3 / "ablation_g3_imdb_ettin_encoder_w10_20260922_191235" / "g3_imdb_ettin_encoder_w10_cycles-10_20260922_191254_000000_s13_ab_cd"
    failed.mkdir(parents=True)
    (failed / "metrics.json").write_text(_json.dumps({"status": "failed"}))
    rerun = g3 / "ablation_g3_imdb_ettin_encoder_w10_bs16_20260922_191655" / "g3_imdb_ettin_encoder_w10_bs16_cycles-10_20260922_201756_000000_s13_ab_cd"
    rerun.mkdir(parents=True)
    (rerun / "metrics.json").write_text(_json.dumps({"heldout_test": {"accuracy": 0.93328}}))
    rows = tp._table2_loop_rows(tmp_path)
    assert [(r["row"], r["column"], r["value"]) for r in rows] == [
        ("ettin_encoder promptillery (10 cycles)", "imdb", "93.33 (bs16)")
    ]
    assert "_bs16_" in rows[0]["file"]

