# =============================================================================
# Text Classification with FastText
# =============================================================================
# Demonstrates knowledge distillation using FastText as the student model.
# FastText is a lightweight, fast text classifier suitable for large-scale
# classification tasks with lower computational requirements.
#
# To run: python -m promptillery.cli train examples/text_classification_fasttext.yaml
# =============================================================================

name: "fasttext_ag_news"
teacher: "openai/gpt-4o-mini"
student: "fasttext"
student_type: "fasttext"

# Dataset: AG News (4-class news classification)
dataset: "SetFit/ag_news"
dataset_config:
  name: "default"
  num_classes: 4
  text_field: "text"
  label_field: "label"

metrics:
  - accuracy
  - f1

# -----------------------------------------------------------------------------
# FASTTEXT HYPERPARAMETERS
# -----------------------------------------------------------------------------
# FastText uses different hyperparameter ranges than transformers:
#   - Higher learning rates (0.1-1.0 vs 1e-5 for transformers)
#   - More training epochs (10-25 vs 2-5 for transformers)

cycles: 5

# FastText-appropriate learning rate
learning_rate: 0.25

# FastText needs more epochs for convergence
num_train_epochs: 15

# Synthetic samples per cycle
augmentation_batch_size: 32

# -----------------------------------------------------------------------------
# EARLY STOPPING
# -----------------------------------------------------------------------------
early_stopping:
  enabled: true
  patience: 2
  metric: "f1"
  mode: "max"
  min_delta: 0.005
  restore_best: true

# -----------------------------------------------------------------------------
# DATA SAMPLING
# -----------------------------------------------------------------------------
sampling:
  enabled: true
  sample_size: 2000
  train_ratio: 0.8
  stratify_column: "label"
  seed: 42

base_output_dir: "experiments/fasttext_classification"

# -----------------------------------------------------------------------------
# TEACHER MODEL PROMPT TEMPLATE
# -----------------------------------------------------------------------------
prompt: |
  You are a teacher model in a knowledge distillation pipeline for news classification.

  # Task Description
  Classify news articles into one of four categories:
  0: World - International news, politics, diplomacy
  1: Sports - Athletic events, teams, players
  2: Business - Finance, markets, economics, companies
  3: Sci/Tech - Science discoveries, technology, gadgets

  # Reference Examples
  {{ format_samples_for_prompt(few_shot_samples, include_prediction=False) }}

  # Student Model Performance
  ```
  {{ classification_report }}
  ```

  # Student Model Errors

  ## High Uncertainty Samples
  {{ format_samples_for_prompt(high_entropy_samples, include_prediction=True) }}

  ## Confident Misclassifications
  {{ format_samples_for_prompt(hard_negative_samples, include_prediction=True) }}

  # Task
  Generate {{ augmentation_batch_size }} new news article samples focusing on:
  1. Categories with low precision/recall scores
  2. Confusion patterns (e.g., Business vs Sci/Tech for tech companies)
  3. Clear examples that reinforce correct category boundaries
  4. Diverse vocabulary and writing styles within each category
