#!/usr/bin/env python
"""Generate the M6 encoder-baseline configs (EACL 2027 resubmission, E1/E2).

Variants per (dataset, student):
  ft1            1 cycle on the gold seed subset, warmup_steps 10   -> Table 2 "fine-tuned (1 cycle)"
  same_n         1 cycle on same-N gold data,     warmup_steps 10   -> Table 2 "same-N gold FT"
  same_n_cm      10 cycles on same-N gold data, package-default warmup (500): the exact
                 per-round schedule of the promptillery arm            -> "same-N gold FT, compute-matched"
  same_n_cm_w10  same-N gold, compute-matched: 10 rounds, warmup_steps 10 -> "same-N gold FT,
                 compute-matched (warm-up 10)": twin of the corrected loop re-runs (#42, #46)
  seed_x10       10 cycles on the gold seed subset, default warmup     -> Appendix "seed-only x10"

Why warmup 10: the EMNLP 2026 reviewers found that the package default of 500
warmup steps never ends in a ~100-step run, so the old 1-cycle baselines were
trained at a tiny learning rate; 10 is the value every decoder config already uses.

    uv run python scripts/gen_m6_configs.py                      # all 50 files
    uv run python scripts/gen_m6_configs.py --only m6_sst2_ft1_roberta_base --batch-size 16 --print-path
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Optional

import yaml

DATASETS = ["agnews", "sst2", "imdb", "yahoo", "huffpost"]
STUDENTS = {"roberta_base": "FacebookAI/roberta-base",
            "ettin_encoder": "jhu-clsp/ettin-encoder-150m"}
VARIANTS = ["ft1", "same_n", "same_n_cm", "same_n_cm_w10", "seed_x10"]
BASELINE_WARMUP = 10
AUGMENTATION_KEYS = ("prompt", "augmentation_batch_size", "teacher_max_output_tokens")

HEADER = """\
# =============================================================================
# M6 -- {title}
# =============================================================================
# GENERATED by scripts/gen_m6_configs.py from {source}; re-run the generator
# instead of hand-editing. {why}
# Zero teacher calls (no prompt key). Output under out/m6. Not CI-verified.
# =============================================================================
"""
TITLES = {
    "ft1": "fine-tuned (1 cycle) on the gold seed subset, warmup_steps 10",
    "same_n": "same-N gold fine-tune (1 cycle), warmup_steps 10",
    "same_n_cm": "same-N gold, compute-matched: 10 rounds, default warmup",
    "same_n_cm_w10": "same-N gold, compute-matched: 10 rounds, warmup_steps 10",
    "seed_x10": "gold seed only, 10 rounds, default warmup (repeated-training control)",
}
WHY = {
    "ft1": "warmup_steps 10: the package default (500) never ends in a ~100-step run.",
    "same_n": "warmup_steps 10: the package default (500) never ends in a ~100-step run.",
    "same_n_cm": "Default warmup on purpose: each of the 10 rounds trains exactly like the promptillery arm.",
    "same_n_cm_w10": "warmup_steps 10 in every round: twins the corrected loop re-runs (#42, #46), "
                      "which also use 10 warm-up steps in every cycle.",
    "seed_x10": "Default warmup on purpose: each of the 10 rounds trains exactly like the promptillery arm.",
}
_NAME = re.compile(r"^m6_(?P<d>[a-z0-9]+)_(?P<v>ft1|same_n_cm_w10|same_n_cm|same_n|seed_x10)_(?P<s>roberta_base|ettin_encoder)(?:_bs\d+)?(?:_s\d+)?$")


def _load(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def parse_name(name: str) -> tuple[str, str, str]:
    m = _NAME.match(name)
    if not m:
        raise ValueError(f"not an M6 run name: {name}")
    return m.group("d"), m.group("v"), m.group("s")


def build(variant: str, dataset: str, student: str, examples: Path,
          batch_size: Optional[int] = None, seed: Optional[int] = None) -> dict:
    if variant in ("ft1", "seed_x10"):
        cfg = dict(_load(examples / f"G3_{dataset}_ettin_encoder.yaml"))
        for key in AUGMENTATION_KEYS:
            cfg.pop(key, None)
        cfg["student"] = STUDENTS[student]
        cfg["cycles"] = 1 if variant == "ft1" else 10
        source = f"G3_{dataset}_ettin_encoder.yaml"
    else:
        cfg = dict(_load(examples / f"M5_{dataset}_same_n_{student}.yaml"))
        cfg["cycles"] = 1 if variant == "same_n" else 10
        source = f"M5_{dataset}_same_n_{student}.yaml"
    if variant in ("ft1", "same_n", "same_n_cm_w10"):
        cfg["warmup_steps"] = BASELINE_WARMUP
    else:
        cfg.pop("warmup_steps", None)
    name = f"m6_{dataset}_{variant}_{student}"
    if batch_size is not None:
        cfg["batch_size"] = batch_size
        name += f"_bs{batch_size}"
    if seed is not None:
        cfg["seed"] = seed
        name += f"_s{seed}"
    cfg["base_output_dir"] = "out/m6"
    cfg["persist_datasets"] = False
    cfg["auto_modify_name"] = False
    cfg["_source"] = source
    return {"name": name, **{k: v for k, v in cfg.items() if k != "name"}}


def write(cfg: dict, examples: Path) -> Path:
    cfg = dict(cfg)
    source = cfg.pop("_source")
    d, v, s = parse_name(cfg["name"])
    suffix = cfg["name"][len(f"m6_{d}_{v}_{s}"):]  # "" or "_bsN"
    path = examples / f"M6_{d}_{v}_{s}{suffix}.yaml"
    header = HEADER.format(title=TITLES[v], source=source, why=WHY[v])
    path.write_text(header + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True),
                    encoding="utf-8")
    return path


_ONLY_SEED = re.compile(r"^(?P<base>.+)_s(?P<seed>\d+)$")


def write_all(examples: Path, only: Optional[str] = None,
              batch_size: Optional[int] = None, seed: Optional[int] = None) -> list[Path]:
    if only and seed is None:
        m = _ONLY_SEED.match(only)
        if m:
            only, seed = m.group("base"), int(m.group("seed"))
    paths = []
    for d in DATASETS:
        for s in STUDENTS:
            for v in VARIANTS:
                if only and only != f"m6_{d}_{v}_{s}":
                    continue
                paths.append(write(build(v, d, s, examples, batch_size, seed), examples))
    return paths


def main(argv=None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--examples", default="examples")
    p.add_argument("--only", default=None, help="an M6 run name without _bsN")
    p.add_argument("--batch-size", type=int, default=None)
    p.add_argument("--seed", type=int, default=None)
    p.add_argument("--print-path", action="store_true")
    args = p.parse_args(argv)
    paths = write_all(Path(args.examples), args.only, args.batch_size, args.seed)
    for path in paths:
        print(path if args.print_path else f"wrote {path}")
    return 0 if paths else 1


if __name__ == "__main__":
    raise SystemExit(main())
