#!/usr/bin/env python
"""Write examples/G3_<D>_roberta_base.yaml: the Ettin-encoder G3 config with RoBERTa
as the student and warmup_steps 10, so the Table 2 RoBERTa promptillery rows can be
re-run from shipped configs (E4)."""
from pathlib import Path

import yaml

DATASETS = ["agnews", "sst2", "imdb", "yahoo", "huffpost"]
HEADER = (
    "# G3 -- tab:main-results, {D}: RoBERTa-base promptillery arm (cycles 1/5/10).\n"
    "# GENERATED by scripts/gen_g3_roberta_configs.py from G3_{D}_ettin_encoder.yaml:\n"
    "# student swapped to FacebookAI/roberta-base; warmup_steps 10 (see M6_README.md).\n"
    "# Needs OPENROUTER_API_KEY; run: uv run promptillery ablation <this file> --no-cleanup\n"
)

for d in DATASETS:
    src = Path("examples") / f"G3_{d}_ettin_encoder.yaml"
    cfg = yaml.safe_load(src.read_text(encoding="utf-8"))
    cfg = {"name": f"g3_{d}_roberta_base", **{k: v for k, v in cfg.items() if k != "name"}}
    cfg["student"] = "FacebookAI/roberta-base"
    cfg["warmup_steps"] = 10
    cfg["trainer_config"] = {k: v for k, v in cfg.get("trainer_config", {}).items() if k != "trust_remote_code"}
    out = Path("examples") / f"G3_{d}_roberta_base.yaml"
    out.write_text(HEADER.format(D=d) + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print("wrote", out)
