#!/usr/bin/env python
"""Write examples/G3_<D>_ettin_encoder_w10.yaml: the Ettin-encoder G3 config with
warmup_steps 10, so the Table 2 Ettin-encoder promptillery rows can be re-run from
shipped configs with the corrected warmup (E4b)."""
from pathlib import Path

import yaml

DATASETS = ["agnews", "sst2", "imdb", "yahoo", "huffpost"]
HEADER = (
    "# G3 -- tab:main-results, {D}: Ettin-encoder promptillery arm re-run with\n"
    "# warmup_steps 10 (cycles 1/5/10).\n"
    "# GENERATED by scripts/gen_g3_ettin_w10_configs.py from G3_{D}_ettin_encoder.yaml.\n"
    "# Needs OPENROUTER_API_KEY; run: uv run promptillery ablation <this file> --no-cleanup\n"
)

for d in DATASETS:
    src = Path("examples") / f"G3_{d}_ettin_encoder.yaml"
    cfg = yaml.safe_load(src.read_text(encoding="utf-8"))
    cfg = {"name": f"g3_{d}_ettin_encoder_w10", **{k: v for k, v in cfg.items() if k != "name"}}
    cfg["warmup_steps"] = 10
    # student_type is "transformers", which is not a substring of the new name, so
    # ExperimentConfig.modify_name_based_on_student_type would otherwise append it.
    cfg["auto_modify_name"] = False
    out = Path("examples") / f"G3_{d}_ettin_encoder_w10.yaml"
    out.write_text(HEADER.format(D=d) + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print("wrote", out)
